#!/bin/bash

read -t 5 -p "是否解压 T507 (5s 超时): " isTar 

if ["isTar" == "y"]; then
	cd ~/zipClass
	sudo ./ubunt_env_install.sh
	sudo tar xvfj TQT507_coreB_linux_V1.1.tar.bz2 -C ~/work/
fi

cd ~/work
~/myBin/change_chownUser leige ~/work
mv ~/work/opt/EmbedSky/TQT507/longan ~/work/
rm -rf ~/work/opt
cd ~/work/longan/
NowWorkPath=$(pwd)
cd brandy/brandy-2.0/u-boot-2018/configs/
cp sun50iw9p1_spinand_ubifs_defconfig ../.config
cd ${NowWorkPath}/buildroot/buildroot-201902/configs/
cp sun50iw9p1_longan_defconfig ../.config
cd ${NowWorkPath}/kernel/linux-4.9/arch/arm64/configs/
cp sun50iw9p1smp_t507_dragonboard_defconfig ../defconfig

cd ~/work/longan/

echo "构建 bootloader >>> ./build.sh coreB bootloader"
echo "构建 rootfs.ext4 >>> ./build.sh coreB ubuntu"
echo "构建 kernel >>> ./build.sh coreB Image"
read -t 5 -p "正在打开 disp_lcd.c "

vim kernel/linux-4.9/drivers/video/fbdev/sunxi/disp2/disp/de/disp_lcd.c +360
vim kernel/linux-4.9/scripts/dtc/dtc-lexer.lex.c_shipped +634
